### ISSUE TITLE
Error 500 / database_user: 'vmail' need more mysql permission ?

### ISSUE THREAD

**Issue by Eisteed** [Andreas-Bresch/vmailManage#17]
Hello I did successfully install everything to setup a mail server with this https://thomas-leister.de/en/mailserver-debian-stretch/ 
Only "custom" thing I did is add sasl authentication
I installed vmailmanage, pages are loading correctly. But every action I do (add domain, add aliases, add users) always get me a 500 internal error and I just can't find where are the logs about it (no error logs in apache2). I guess the problem is that the database user vmail need writing permission to the sql database but I was wondering if this is still secure to do so or is there anything else to do.
Thanks for the help.

**Comment by Sputnik2Space** [comment]
Hello also receiving error 500 and this is what I get in apache error.log 

PHP Fatal error:  Uncaught Error: Call to a member function getAttributeNS() on null in /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:553\nStack trace:\n#0 [internal function]: Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->validateSchema(Object(DOMDocument), false)\n#1 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/Config/Util/XmlUtils.php(78): call_user_func(Array, Object(DOMDocument), false)\n#2 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(368): Symfony\\Component\\Config\\Util\\XmlUtils::loadFile('/var/www/html/v...', Array)\n#3 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php(41): Symfony\\Component\\DependencyInjection\\Loader\\XmlFileLoader->parseFileToDOM('/var/www/html/v...')\n#4 /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Framework in /var/www/html/vmailManage/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 553

**Comment by maxbax0808** [comment]
Having the same Issue :(
Did anyone of you solve it?

**Comment by baciatore** [comment]
If anybody need help for this Problem:
Update the permissions of the vmail database user to allow insert, update and delete queries:
`grant select, insert, update, delete on vmail.* to 'vmail'@'localhost' identified by 'vmaildbpass';`
